### ISSUE TITLE
Re-licensing.

### ISSUE THREAD

**Issue by avhz** [avhz/RustQuant#109]
I would like to change from GPL3 license to dual Apache/MIT licenses, as this is less restrictive and hopefully will increase contributions and usage. 

Since you have all made contributions, could you comment your approval (or disapproval and reasoning) ?

- [x] @Autoparallel 
- [x] @aatmunbaxi 
- [x] @dancixx 
- [x] @chammika-become 
- [x] @joshleveck 
- [x] @Uzaaft 
- [x] @AdRiley 
- [x] @SimonG85 
- [x] @s3bru 
- [x] @LucaSchinnerlBain 

Thanks in advance ! :)

**Comment by dancixx** [comment]
Lets do it. Community needs a good math finance package in rust. 🙂

**Comment by LucaSchinnerlBain** [comment]
I love it!

**Comment by chammika-become** [comment]
Sure! I am all for less restrictive licensing for OSS projects 👍

**Comment by Uzaaft** [comment]
LGTM🚀

**Comment by s3bru** [comment]
ok

**Comment by joshleveck** [comment]
Sounds like a great idea!

**Comment by AdRiley** [comment]
Yes sounds good to me too!

**Comment by aatmunbaxi** [comment]
Sounds good

**Comment by Autoparallel** [comment]
Sounds good to me. I trust your decision making!

**Comment by SimonG85** [comment]
Completely agree!
