### ISSUE TITLE
Remove some camel case.

### ISSUE THREAD

**Issue by avhz** [avhz/RustQuant#13]
Binomial option pricer has it. Possibly elsewhere ?

**Comment by SimonG85** [comment]
valuationDate in src/instruments/instrument.rs:21:8
time_T in src/bonds/vasicek.rs:29:5, src/bonds/vasicek.rs:39:13
n_C_k in src/distributions/binomial.rs:41:13
dW in src/stochastics/process.rs:66:17
K_1 in src/options/binary.rs:67:13
K_2 in src/options/binary.rs:68:13
price_CoxRossRubinstein in src/options/binomial.rs:43:12
AmeEurFlag in src/options/binomial.rs:46:9
CallPutFlag in src/options/binomial.rs:47:9
OptionValue in src/options/binomial.rs:57:17
ReturnValue in src/options/binomial.rs:59:17
Driftless_theta in src/options/greeks.rs:29:9 (and for the greeks in general)
There are a lot of T, K, S.
Would you like to remove all non camel cases?
