### ISSUE TITLE
Include all features on docs.rs. 

### ISSUE THREAD

**Issue by avhz** [avhz/RustQuant#136]
Docs.rs does not include the `data` module as it is hidden behind the `data` feature. I want the module to be shown on the front page of docs.rs along with all the other modules.

**Comment by CharonEXE** [comment]
Hi, I wonder if this issue still active ?

**Comment by avhz** [comment]
Hi, sorry for the extremely long delay in responding. 

Yes this is available :)

**Comment by CharonEXE** [comment]
Hi, don't mention it and thanks for your kind response.

Back to the topic, may I take this issue? 
I am still picking up to both Rust and GitHub ecosystem, if you don't mind.

**Comment by CharonEXE** [comment]
Hi, don't mention it and thanks for your kind response.

Back to the topic, may I take this issue? 
I am still picking up to both Rust and GitHub ecosystem, if you don't mind.
