### ISSUE TITLE
feat(stochastics): Have time-varying parameters for processes

### ISSUE THREAD

**Issue by Autoparallel** [avhz/RustQuant#145]
# Idea
It would be helpful to have time-varying parameters for stochastic processes. This way we can model richer price action and other dynamics with this package. We can do so with minimal changesin the API as this will only be an extension.

## Solution

Let's take for example the `GeometricBrownianMotion`. First, let me define a new type:
```rust
pub struct TimeDependent(pub Box<dyn Fn(f64) -> f64 + Send + Sync>);

impl From<f64> for TimeDependent {
    fn from(x: f64) -> Self {
        Self(Box::new(move |_| x))
    }
}
```
which can rest in the `process.rs` module (or elsewhere if we want).

Now, we have to modify `GeometricBrownianMotion` like so:
```rust
pub struct GeometricBrownianMotion {
    /// The drift ($\mu$) in percentage.
    pub mu: TimeDependent,

    /// The volatility ($\sigma$) in percentage.
    pub sigma: TimeDependent,
}

impl GeometricBrownianMotion {
    /// Create a new Geometric Brownian Motion process.
    pub fn new(mu: impl Into<TimeDependent>, sigma: impl Into<TimeDependent>) -> Self {
        assert!(sigma >= 0.0); // TODO: Move this assert into the euler maruma function.
        Self {
            mu: mu.into(),
            sigma: sigma.into(),
        }
    }
}

impl StochasticProcess for GeometricBrownianMotion {
    fn drift(&self, x: f64, t: f64) -> f64 {
        // mu X_t dt
        self.mu.0(t) * x
    }

    fn diffusion(&self, x: f64, t: f64) -> f64 {
        // sigma X_t dW_t
        self.sigma.0(t) * x
    }

    fn jump(&self, _x: f64, _t: f64) -> f64 {
        0.0
    }
}
```
Noted in the snippet above, we will have to move the assertion into `StochasticProcess::euler_maruyama()` or perhaps into the `GeometricBrownianMotion::drift()` method and simply check `self.sigma.0.(t)>=0.0` when called. This could lead to a minor footgun, but for me the feature is worth it. I am also willing to add better error handling here to alert the end user more specifically of what failed rather than a straight up panic.

---

Let me know what you think! Happy to run with this and apply it to each of the processes we have here already.

**Comment by avhz** [comment]
We already have a few non-autonomous processes (Ho-Lee, Hull-White, etc) in a similar fashion however without defining a new type. 
I like your idea of implementing From<f64>. 

But I assume you mean generalising every process' parameters to be possibly time-dependent ?

**Comment by Autoparallel** [comment]
Correct!

**Comment by avhz** [comment]
I like the idea, the only possible issue I have is that I was planning on moving the stochastic process parameter structs to a new module `models` since they can be quite general and used both for the stochastic process generators and also for pricing bonds, for example. I would also do the same with `BlackScholesMerton` in the `options` module.

But if we can somehow maintain the ability to `impl` various traits on a parameter struct but also include time dependent parameters that would be very nice. 

Do you have any ideas? 

If you wish to implement it regardless as it is useful, go ahead of course, the idea is great. And I can always adjust later if I figure a way to do both.

**Comment by Autoparallel** [comment]
Let me take a look. If we use good `impl` I think we will be okay.

Let me ship this as well and I can collab with you on genralizing to models

**Comment by avhz** [comment]
Perfect, I love the idea, thanks a lot.
