### ISSUE TITLE
Use Release-Plz for automatic releases. 

### ISSUE THREAD

**Issue by 0xJepsen** [avhz/RustQuant#150]
We recently started using this tool [Release-plz](https://release-plz.ieni.dev/) for automatic releases with [arbiter](https://github.com/primitivefinance/arbiter) it was recommended to me by some friends who work on [Noir Lang](https://github.com/noir-lang) and i have been very impressed with the tool. Every moment there are diffs between the current latest release and what is in main it will ship a PR that auto detects semantic versioning and increments tomls. It also generates a release tag and publishes to crates if you give it the crates api token. If you like i can ship a PR to add this (Although you will have to configure the github token to have it auto publish to crates)

**Comment by avhz** [comment]
Love the idea

**Comment by 0xJepsen** [comment]
So I can help you do this but you need to set up the api key for crates and the actions bots.

**Comment by avhz** [comment]
Sure, I can try to do it on Sunday, or possibly some time next week.

**Comment by 0xJepsen** [comment]
Awesome I found it made managing the repo lots easier for me :)

**Comment by avhz** [comment]
Did you ever come across this issue when the action runs?

```
2023-11-12T17:24:15.687677Z ERROR  the working directory of this project has uncommitted changes. Please commit or stash these changes:
Error: the working directory of this project has uncommitted changes. Please commit or stash these changes:
[".vscode/settings.json"]
[".vscode/settings.json"]
```

**Comment by avhz** [comment]
I sorted it. Thanks for idea !
