### ISSUE TITLE
Implied volatility calculation

### ISSUE THREAD

**Issue by lukaskiss222** [avhz/RustQuant#154]
Hi,

I noticed that our codebase lacks a function to calculate implied volatility from an option price. I plan to implement this feature using the paper ["Let's Be Rational"](http://www.jaeckel.org/LetsBeRational.pdf) by [Peter Jäckel](http://jaeckel.org/).

Could you guide me to the appropriate location within the codebase to integrate this feature? I'm having trouble identifying the most suitable place for its implementation.

**Comment by MeetThePatel** [comment]
Would it make sense to put it in `src/instruments/options`? `greeks.rs` is in that directory, so would it make sense to put implied volatility computation in `src/instruments/options/implied_volatility.rs` or `src/instruments/options/iv.rs`?


Also, with regards to the actual IV calculation: do you know if that method is faster than successive over-relation (https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1027282). Just from a cursory reading, it seems that the order of convergence of Halley's method is cubic and the order of convergence of successive over-relation is quadratic (after some transformations); however, I'm not sure as to how that translates into actual runtime.

**Comment by avhz** [comment]
Hi @lukaskiss222 thanks for your interest! Sorry for my delayed response, I'm very busy at the moment.

Having an IV implementation is needed for sure, so I'd definitely welcome your contribution. 

The appropriate place would be `./src/instruments/options/implied_volatility.rs` as @MeetThePatel suggested. I would prefer more descriptive names (e.g. `implied_volatility` over `iv`).

I am not particularly fussed over the specific algorithm, my preference would just be a user-friendly API. In saying that, for something like IV, I would say faster is better. I'm not familiar with the Li & Lee paper though, and I don't have the time at the moment to read it in detail unfortunately. So it may be that their algorithm is faster. 
But Jaeckel's is very well established and fast as far as I am aware, and if you (@lukaskiss222) are familiar with it, by all means go with his.

**Comment by lukaskiss222** [comment]
Hi @avhz and @MeetThePatel,

Thank you both for your valuable inputs. I appreciate the direction regarding the placement of the implied volatility function. Following your suggestions, I will proceed with implementing the feature in `./src/instruments/options/implied_volatility.rs` and ensure that the naming is clear and descriptive.

Regarding the choice of algorithm, I agree with @avhz that a user-friendly and fast solution is crucial. I'm confident in working with Peter Jäckel's method as it's well-established and known for its efficiency. I'll focus on implementing this method first, ensuring it integrates smoothly into our codebase with an emphasis on speed and ease of use.

@MeetThePatel, your suggestion to compare Jäckel's method with the Li & Lee method is intriguing. It could provide us with valuable insights into the performance trade-offs between these two approaches. If you're willing to implement the Li & Lee method, we could run a comparative analysis to evaluate their respective performances. This could be a great way to ensure we're providing the most efficient solution in our codebase.

I'll start working on the Jäckel implementation and keep you both updated on my progress. Looking forward to seeing how the Li & Lee implementation shapes up as well, if you decide to go ahead with it.

**Comment by avhz** [comment]
Thanks so much for this @lukaskiss222. 

I moved the module out so that it's not nested. If we add other implementations in the future we can create another sub-module.

Thanks again, nice work.
