### ISSUE TITLE
Can we support built-in "factor analysis"?

### ISSUE THREAD

**Issue by uiosun** [avhz/RustQuant#178]
Hi, I'm new to both Rust and Quant!

In the future, can we support a tool with built-in "factor analysis"? Looking forward to use it to test factors like "Short-term Reversal", "Momentum effect".

What do I need to implement it? If somebody have time, please tell me some terms or links to tutorials, I would like to implement this!

**Comment by avhz** [comment]
Hi thanks for your interest in RustQuant !

What do you mean by tool ? This is usually a higher level time series analysis, which something like Python or R would probably be more suited for. 
You could use Polars in Rust (or Python) to perform this analysis too. 

What would you suggest this tool does for the end user ?

**Comment by uiosun** [comment]
Hi, I read more about compile time.

If I were analyzing the momentum factor, and every time I made a change, I had to wait a minute or more to compile it, I would crash ......

But if you analyze long cycles, the performance of Rust would be an advantage for a normal computer?

So now I'm agreeing with you about putting them in Python or R.

Or does Rust have a tool like Jupyter Notebook (I found https://github.com/evcxr/evcxr but haven't tried it yet)

**Comment by avhz** [comment]
Yes, Rust is a compiled language. 
This is the reason I suggested an interpreted language like Python, R, Julia, etc. for your task. 

I have not used that tool you mentioned, it may be good. 
I would personally look at Polars or Pandas (in Python) for this sort of data analysis.
