### ISSUE TITLE
doc.rs failed to build

### ISSUE THREAD

**Issue by qiweiii** [avhz/RustQuant#191]
**Describe the bug**
doc.rs says failed to build

**To Reproduce**
1. Go to https://docs.rs/crate/RustQuant/latest

**Expected behavior**
docr.rs can show the latest content

**Comment by avhz** [comment]
Hi thanks for the report.
I'm aware of the issue, it's a problem due to docs building with nightly and a problem with pathfinder_simd dependency, which I'm waiting to hear from the maintainers about.
