### ISSUE TITLE
Inconsistency between code and documentation

### ISSUE THREAD

**Issue by YichiZhang0613** [avhz/RustQuant#203]
There is inconsistency between code and documentation In RustQuant/src/math/distributions/exponential.rs, the documentation requires lambda <= 0.0, while the code checks assert!(lambda > 0.0);
```rust
/// # Panics
    ///
    /// Panics if lambda is greater than 0.0
    #[must_use]
    pub fn new(lambda: f64) -> Self {
        assert!(lambda > 0.0);

        Self { lambda }
    }
```

**Comment by avhz** [comment]
Thanks for spotting. Fixed in commit commit 9f102b30c9d3edf204b3bac3783f78627441d660
