### ISSUE TITLE
x86_64-pc-windows-gnu vs x86_64-pc-windows-msvc

### ISSUE THREAD

**Issue by harry4939** [avhz/RustQuant#215]
I'm newbie, so forgive me if the question seems silly
### Description:
Issues:

1. In my forked RustQuant project, executing examples works fine, but debugging doesn't,the breakpoint cannot be hit.
2. When I include RustQuant as a dependency in my own test project, compiled exe files with x86_64-pc-windows-gnu toolchain cannot execute, showing the error: "%1 is not a valid Win32 application".
3.  However, switching to x86_64-pc-windows-msvc toolchain allows the generated exe file to run and debug correctly.

Operating System: Windows 10
Rust Toolchain: stable-x86_64-pc-windows-gnu
linker:
[target.x86_64-pc-windows-gnu]
linker = "C:\\msys64\\ucrt64\\bin\\gcc.exe"
ar = "C:\\msys64\\ucrt64\\bin\\ar.exe"
### To Reproduce:
```
//Cargo.toml
[package]
name = "rest"
version = "0.1.0"
edition = "2021"
[dependencies]
RustQuant = "0.2.3"
```
............................................................................
```
//main.rs

use RustQuant::autodiff::*;

fn main() {
// Create a new Graph to store the computations.
let g = Graph::new();
// Assign variables.
let x = g.var(69.);
let y = g.var(420.);

// Define a function.
let f = {
  let a = x.powi(2);
  let b = y.powi(2);

  a + b + (x * y).exp()
};

// Accumulate the gradient.
let gradient = f.accumulate();

println!("Function = {}", f);
println!("Gradient = {:?}", gradient.wrt([x, y]));
}
```
...............................................................................................................

### Expected behavior:
To be able to compile and debug under the x86_64-pc-windows-gnu toolchain.

**Comment by avhz** [comment]
I don't have a windows machine, but can you share the commands you're running and the output please?

**Comment by harry4939** [comment]
ok
### stable-x86_64-pc-windows-gnu
1. toolchain:`stable-x86_64-pc-windows-gnu  `
2. command: `cargo run`
3. terminal output:
    `$ cargo run
   Compiling autocfg v1.2.0
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.80
   Compiling unicode-ident v1.0.12
   Compiling getrandom v0.2.14
   Compiling version_check v0.9.4
   Compiling libm v0.2.8
   Compiling num-traits v0.2.18
   Compiling rand_core v0.6.4
   Compiling ppv-lite86 v0.2.17
   Compiling rand_chacha v0.3.1
   Compiling quote v1.0.36
   Compiling syn v2.0.59
   Compiling rand v0.8.5
   Compiling siphasher v0.3.11
   Compiling jobserver v0.1.30
   Compiling cc v1.0.94
   Compiling once_cell v1.19.0
   Compiling windows_x86_64_gnu v0.48.5
   Compiling windows_x86_64_gnu v0.52.5
   Compiling crossbeam-utils v0.8.19
   Compiling serde v1.0.197
   Compiling windows-targets v0.48.5
   Compiling windows-targets v0.52.5
   Compiling crossbeam-epoch v0.9.18
   Compiling rayon-core v1.12.1
   Compiling crossbeam-deque v0.8.5
   Compiling syn v1.0.109
   Compiling either v1.11.0
   Compiling ahash v0.8.11
   Compiling rayon v1.10.0
   Compiling zerocopy v0.7.32
   Compiling num-integer v0.1.46
   Compiling itoa v1.0.11
   Compiling serde_derive v1.0.197
   Compiling bytemuck_derive v1.6.0
   Compiling allocator-api2 v0.2.18
   Compiling hashbrown v0.14.3
   Compiling bytemuck v1.15.0
   Compiling static_assertions v1.1.0
   Compiling num-complex v0.4.5
   Compiling winapi-x86_64-pc-windows-gnu v0.4.0
   Compiling phf_shared v0.11.2
   Compiling lock_api v0.4.11
   Compiling winapi v0.3.9
   Compiling parking_lot_core v0.9.9
   Compiling regex-syntax v0.8.3
   Compiling equivalent v1.0.1
   Compiling libc v0.2.153
   Compiling indexmap v2.2.6
   Compiling regex-automata v0.4.6
   Compiling ryu v1.0.17
   Compiling pkg-config v0.3.30
   Compiling smallvec v1.13.2
   Compiling scopeguard v1.2.0
   Compiling regex v1.10.4
   Compiling zstd-sys v2.0.10+zstd.1.5.6
   Compiling phf_generator v0.11.2
   Compiling strength_reduce v0.2.4
   Compiling memchr v2.7.2
   Compiling thiserror v1.0.58
   Compiling phf_codegen v0.11.2
   Compiling parking_lot v0.12.1
   Compiling aho-corasick v1.1.3
   Compiling parse-zoneinfo v0.3.0
   Compiling phf v0.11.2
   Compiling thiserror-impl v1.0.58
   Compiling windows-sys v0.52.0
   Compiling bitflags v2.5.0
   Compiling bytes v1.6.0
   Compiling target-features v0.1.6
   Compiling array-init-cursor v0.2.0
   Compiling planus v0.3.1
   Compiling chrono-tz-build v0.2.1
   Compiling lz4-sys v1.9.4
   Compiling chrono v0.4.37
   Compiling smartstring v1.0.1
   Compiling matrixmultiply v0.3.8
   Compiling zstd-safe v7.1.0
   Compiling simdutf8 v0.1.4
   Compiling chrono-tz v0.8.6
   Compiling polars-arrow-format v0.1.0
   Compiling polars-utils v0.38.3
   Compiling pin-project-lite v0.2.14
   Compiling rawpointer v0.2.1
   Compiling polars-error v0.38.3
   Compiling multiversion-macros v0.7.4
   Compiling raw-cpuid v11.0.1
   Compiling phf_shared v0.10.0
   Compiling polars-arrow v0.38.3
   Compiling fnv v1.0.7
   Compiling serde_json v1.0.115
   Compiling log v0.4.21
   Compiling multiversion v0.7.4
   Compiling windows-sys v0.48.0
   Compiling atoi v2.0.0
   Compiling itoap v1.0.1
   Compiling simd-adler32 v0.3.7
   Compiling dyn-clone v1.0.17
   Compiling rustversion v1.0.15
   Compiling fast-float v0.2.0
   Compiling foreign_vec v0.1.0
   Compiling crc32fast v1.4.0
   Compiling atoi_simd v0.15.6
   Compiling ethnum v1.5.0
   Compiling streaming-iterator v0.1.9
   Compiling lexical-util v0.8.5
   Compiling adler v1.0.2
   Compiling futures-core v0.3.30
   Compiling miniz_oxide v0.7.2
   Compiling mio v0.8.11
   Compiling phf_generator v0.10.0
   Compiling socket2 v0.5.6
   Compiling ring v0.17.8
   Compiling rand_distr v0.4.3
   Compiling base64 v0.21.7
   Compiling heck v0.4.1
   Compiling tokio v1.37.0
   Compiling lz4 v1.24.0
   Compiling flate2 v1.0.28
   Compiling ndarray v0.15.6
   Compiling crossterm_winapi v0.9.1
   Compiling polars-compute v0.38.3
   Compiling new_debug_unreachable v1.0.6
   Compiling percent-encoding v2.3.1
   Compiling semver v1.0.22
   Compiling crossterm v0.27.0
   Compiling strum_macros v0.26.2
   Compiling string_cache_codegen v0.5.2
   Compiling phf_codegen v0.10.0
   Compiling lexical-parse-integer v0.8.6
   Compiling lexical-write-integer v0.8.5
   Compiling polars-core v0.38.3
   Compiling num-bigint v0.4.4
   Compiling unicode-width v0.1.11
   Compiling ref-cast v1.0.22
   Compiling spin v0.9.8
   Compiling alloc-no-stdlib v2.0.4
   Compiling mac v0.1.1
   Compiling untrusted v0.9.0
   Compiling strum v0.26.2
   Compiling alloc-stdlib v0.2.2
   Compiling futf v0.1.5
   Compiling comfy-table v7.1.1
   Compiling lexical-write-float v0.8.5
   Compiling zstd v0.13.1
   Compiling lexical-parse-float v0.8.5
   Compiling markup5ever v0.11.0
   Compiling halfbrown v0.2.5
   Compiling ref-cast-impl v1.0.22
   Compiling tracing-core v0.1.32
   Compiling float-cmp v0.9.0
   Compiling polars-ops v0.38.3
   Compiling num-rational v0.4.1
   Compiling slab v0.4.9
   Compiling unicode-segmentation v1.11.0
   Compiling snap v1.1.1
   Compiling paste v1.0.14
   Compiling xxhash-rust v0.8.10
   Compiling utf-8 v0.7.6
   Compiling fallible-streaming-iterator v0.1.9
   Compiling precomputed-hash v0.1.1
   Compiling string_cache v0.8.7
   Compiling tendril v0.4.3
   Compiling unicode-reverse v1.0.9
   Compiling tracing v0.1.40
   Compiling value-trait v0.8.1
   Compiling rustc_version v0.4.0
   Compiling lexical-core v0.8.5
   Compiling brotli-decompressor v2.5.1
   Compiling http v0.2.12
   Compiling polars-row v0.38.3
   Compiling phf v0.10.1
   Compiling safe_arch v0.7.1
   Compiling argminmax v0.6.2
   Compiling ident_case v1.0.1
   Compiling futures-task v0.3.30
   Compiling pin-utils v0.1.0
   Compiling httparse v1.8.0
   Compiling rustls v0.21.10
   Compiling strsim v0.10.0
   Compiling futures-sink v0.3.30
   Compiling tinyvec_macros v0.1.1
   Compiling hex v0.4.3
   Compiling tinyvec v1.6.0
   Compiling tokio-util v0.7.10
   Compiling darling_core v0.20.8
   Compiling futures-util v0.3.30
   Compiling wide v0.7.15
   Compiling brotli v3.5.0
   Compiling pathfinder_simd v0.5.3
   Compiling simd-json v0.13.9
   Compiling streaming-decompression v0.1.2
   Compiling sct v0.7.1
   Compiling rustls-webpki v0.101.7
   Compiling now v0.1.3
   Compiling html5ever v0.26.0
   Compiling approx v0.5.1
   Compiling rustfft v6.2.0
   Compiling bitflags v1.3.2
   Compiling seq-macro v0.3.5
   Compiling parquet-format-safe v0.2.4
   Compiling try-lock v0.2.5
   Compiling typenum v1.17.0
   Compiling want v0.3.1
   Compiling polars-parquet v0.38.3
   Compiling h2 v0.3.26
   Compiling polars-time v0.38.3
   Compiling polars-json v0.38.3
   Compiling darling_macro v0.20.8
   Compiling unicode-normalization v0.1.23
   Compiling http-body v0.4.6
   Compiling form_urlencoded v1.2.1
   Compiling futures-channel v0.3.30
   Compiling fdeflate v0.3.4
   Compiling home v0.5.9
   Compiling winapi-util v0.1.6
   Compiling transpose v0.2.3
   Compiling primal-check v0.3.3
   Compiling polars-plan v0.38.3
   Compiling unicode-bidi v0.3.15
   Compiling lazy_static v1.4.0
   Compiling memmap2 v0.7.1
   Compiling byteorder v1.5.0
   Compiling tower-service v0.3.2
   Compiling httpdate v1.0.3
   Compiling color_quant v1.1.0
   Compiling hyper v0.14.28
   Compiling polars-io v0.38.3
   Compiling idna v0.5.0
   Compiling same-file v1.0.6
   Compiling png v0.17.13
   Compiling darling v0.20.8
   Compiling tokio-rustls v0.24.1
   Compiling xml5ever v0.17.0
   Compiling strum_macros v0.25.3
   Compiling wio v0.2.2
   Compiling polars-lazy v0.38.3
   Compiling bit-vec v0.6.3
   Compiling powerfmt v0.2.0
   Compiling num-conv v0.1.0
   Compiling plotters-backend v0.3.5
   Compiling weezl v0.1.8
   Compiling jpeg-decoder v0.3.1
   Compiling time-core v0.1.2
   Compiling font-kit v0.11.0
   Compiling image v0.24.9
   Compiling time-macros v0.2.18
   Compiling gif v0.12.0
   Compiling deranged v0.3.11
   Compiling bit-set v0.5.3
   Compiling dwrote v0.11.0
   Compiling markup5ever_rcdom v0.2.0
   Compiling hyper-rustls v0.24.2
   Compiling pathfinder_geometry v0.5.1
   Compiling derive_builder_core v0.20.0
   Compiling walkdir v2.5.0
   Compiling url v2.5.0
   Compiling serde_urlencoded v0.7.1
   Compiling simba v0.6.0
   Compiling rustls-pemfile v1.0.4
   Compiling winreg v0.50.0
   Compiling nalgebra-macros v0.1.0
   Compiling async-stream-impl v0.3.5
   Compiling num-iter v0.1.44
   Compiling polars v0.38.3
   Compiling encoding_rs v0.8.34
   Compiling rust_decimal v1.35.0
   Compiling ipnet v2.9.0
   Compiling sync_wrapper v0.1.2
   Compiling glob v0.3.1
   Compiling webpki-roots v0.25.4
   Compiling float-ord v0.2.0
   Compiling mime v0.3.17
   Compiling reqwest v0.11.27
   Compiling num v0.4.2
   Compiling async-stream v0.3.5
   Compiling nalgebra v0.29.0
   Compiling derive_builder_macro v0.20.0
   Compiling select v0.6.0
   Compiling time v0.3.36
   Compiling plotters-bitmap v0.3.3
   Compiling plotters-svg v0.3.5
   Compiling rustdct v0.7.1
   Compiling realfft v3.3.0
   Compiling simba v0.8.1
   Compiling tokio-stream v0.1.15
   Compiling nalgebra-macros v0.2.1
   Compiling arrayvec v0.7.4
   Compiling ttf-parser v0.17.1
   Compiling plotters v0.3.5
   Compiling nalgebra v0.32.5
   Compiling tokio-test v0.4.4
   Compiling ndrustfft v0.4.2
   Compiling yahoo_finance_api v2.1.0
   Compiling derive_builder v0.20.0
   Compiling statrs v0.16.0
   Compiling errorfunctions v0.2.0
   Compiling ndarray-rand v0.14.0
   Compiling RustQuant v0.2.3
   Compiling rest v0.1.0 (G:\work\Program\RustCode\rest)
    Finished dev [unoptimized + debuginfo] target(s) in 7m 36s
     Running `target\debug\rest.exe`
error: could not execute process `target\debug\rest.exe` (never executed)
Caused by:
  %1 is not a valid Win32 application. (os error 193)`
4. .\target\.rustc_info.json:
    {"rustc_fingerprint":9017840200824476409,"outputs":{"15729799797837862367":{"success":true,"status":"","code":0,"stdout":"___.exe\nlib___.rlib\n___.dll\n___.dll\nlib___.a\n___.dll\nC:\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\noff\n___\ndebug_assertions\npanic=\"unwind\"\nproc_macro\ntarget_arch=\"x86_64\"\ntarget_endian=\"little\"\ntarget_env=\"gnu\"\ntarget_family=\"windows\"\ntarget_feature=\"fxsr\"\ntarget_feature=\"sse\"\ntarget_feature=\"sse2\"\ntarget_has_atomic=\"16\"\ntarget_has_atomic=\"32\"\ntarget_has_atomic=\"64\"\ntarget_has_atomic=\"8\"\ntarget_has_atomic=\"ptr\"\ntarget_os=\"windows\"\ntarget_pointer_width=\"64\"\ntarget_vendor=\"pc\"\nwindows\n","stderr":""},"4614504638168534921":{"success":true,"status":"","code":0,"stdout":"rustc 1.77.2 (25ef9e3d8 2024-04-09)\nbinary: rustc\ncommit-hash: 25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\ncommit-date: 2024-04-09\nhost: x86_64-pc-windows-gnu\nrelease: 1.77.2\nLLVM version: 17.0.6\n","stderr":""}},"successes":{}}``

### stable-x86_64-pc-windows-msvc
1. toolchain:`stable-x86_64-pc-windows-msvc  `
2. command: `cargo run`
3. terminal output:
   ```
    $ cargo run
   Compiling autocfg v1.2.0
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.80
   Compiling unicode-ident v1.0.12
   Compiling getrandom v0.2.14
   Compiling version_check v0.9.4
   Compiling libm v0.2.8
   Compiling num-traits v0.2.18
   Compiling rand_core v0.6.4
   Compiling ppv-lite86 v0.2.17
   Compiling rand_chacha v0.3.1
   Compiling siphasher v0.3.11
   Compiling rand v0.8.5
   Compiling quote v1.0.36
   Compiling jobserver v0.1.30
   Compiling syn v2.0.59
   Compiling cc v1.0.94
   Compiling once_cell v1.19.0
   Compiling windows_x86_64_msvc v0.48.5
   Compiling crossbeam-utils v0.8.19
   Compiling windows_x86_64_msvc v0.52.5
   Compiling serde v1.0.197
   Compiling windows-targets v0.48.5
   Compiling crossbeam-epoch v0.9.18
   Compiling windows-targets v0.52.5
   Compiling rayon-core v1.12.1
   Compiling either v1.11.0
   Compiling crossbeam-deque v0.8.5
   Compiling syn v1.0.109
   Compiling ahash v0.8.11
   Compiling zerocopy v0.7.32
   Compiling rayon v1.10.0
   Compiling num-integer v0.1.46
   Compiling allocator-api2 v0.2.18
   Compiling serde_derive v1.0.197
   Compiling bytemuck_derive v1.6.0
   Compiling itoa v1.0.11
   Compiling hashbrown v0.14.3
   Compiling bytemuck v1.15.0
   Compiling static_assertions v1.1.0
   Compiling num-complex v0.4.5
   Compiling phf_shared v0.11.2
   Compiling lock_api v0.4.11
   Compiling regex-syntax v0.8.3
   Compiling equivalent v1.0.1
   Compiling parking_lot_core v0.9.9
   Compiling winapi v0.3.9
   Compiling libc v0.2.153
   Compiling regex-automata v0.4.6
   Compiling indexmap v2.2.6
   Compiling ryu v1.0.17
   Compiling scopeguard v1.2.0
   Compiling smallvec v1.13.2
   Compiling pkg-config v0.3.30
   Compiling regex v1.10.4
   Compiling phf_generator v0.11.2
   Compiling strength_reduce v0.2.4
   Compiling zstd-sys v2.0.10+zstd.1.5.6
   Compiling memchr v2.7.2
   Compiling thiserror v1.0.58
   Compiling aho-corasick v1.1.3
   Compiling phf_codegen v0.11.2
   Compiling parse-zoneinfo v0.3.0
   Compiling parking_lot v0.12.1
   Compiling phf v0.11.2
   Compiling thiserror-impl v1.0.58
   Compiling windows-sys v0.52.0
   Compiling array-init-cursor v0.2.0
   Compiling bytes v1.6.0
   Compiling target-features v0.1.6
   Compiling bitflags v2.5.0
   Compiling planus v0.3.1
   Compiling chrono-tz-build v0.2.1
   Compiling chrono v0.4.37
   Compiling lz4-sys v1.9.4
   Compiling smartstring v1.0.1
   Compiling matrixmultiply v0.3.8
   Compiling zstd-safe v7.1.0
   Compiling simdutf8 v0.1.4
   Compiling chrono-tz v0.8.6
   Compiling polars-arrow-format v0.1.0
   Compiling polars-utils v0.38.3
   Compiling rawpointer v0.2.1
   Compiling pin-project-lite v0.2.14
   Compiling polars-error v0.38.3
   Compiling multiversion-macros v0.7.4
   Compiling raw-cpuid v11.0.1
   Compiling phf_shared v0.10.0
   Compiling polars-arrow v0.38.3
   Compiling serde_json v1.0.115
   Compiling fnv v1.0.7
   Compiling log v0.4.21
   Compiling multiversion v0.7.4
   Compiling lz4 v1.24.0
   Compiling zstd v0.13.1
   Compiling windows-sys v0.48.0
   Compiling atoi v2.0.0
   Compiling crc32fast v1.4.0
   Compiling ethnum v1.5.0
   Compiling dyn-clone v1.0.17
   Compiling foreign_vec v0.1.0
   Compiling simd-adler32 v0.3.7
   Compiling fast-float v0.2.0
   Compiling atoi_simd v0.15.6
   Compiling rustversion v1.0.15
   Compiling itoap v1.0.1
   Compiling streaming-iterator v0.1.9
   Compiling lexical-util v0.8.5
   Compiling futures-core v0.3.30
   Compiling adler v1.0.2
   Compiling mio v0.8.11
   Compiling miniz_oxide v0.7.2
   Compiling phf_generator v0.10.0
   Compiling socket2 v0.5.6
   Compiling ring v0.17.8
   Compiling rand_distr v0.4.3
   Compiling base64 v0.21.7
   Compiling heck v0.4.1
   Compiling tokio v1.37.0
   Compiling flate2 v1.0.28
   Compiling ndarray v0.15.6
   Compiling crossterm_winapi v0.9.1
   Compiling polars-compute v0.38.3
   Compiling semver v1.0.22
   Compiling percent-encoding v2.3.1
   Compiling new_debug_unreachable v1.0.6
   Compiling crossterm v0.27.0
   Compiling strum_macros v0.26.2
   Compiling string_cache_codegen v0.5.2
   Compiling phf_codegen v0.10.0
   Compiling lexical-parse-integer v0.8.6
   Compiling lexical-write-integer v0.8.5
   Compiling polars-core v0.38.3
   Compiling num-bigint v0.4.4
   Compiling alloc-no-stdlib v2.0.4
   Compiling spin v0.9.8
   Compiling untrusted v0.9.0
   Compiling mac v0.1.1
   Compiling unicode-width v0.1.11
   Compiling ref-cast v1.0.22
   Compiling strum v0.26.2
   Compiling futf v0.1.5
   Compiling comfy-table v7.1.1
   Compiling alloc-stdlib v0.2.2
   Compiling lexical-write-float v0.8.5
   Compiling lexical-parse-float v0.8.5
   Compiling markup5ever v0.11.0
   Compiling polars-row v0.38.3
   Compiling halfbrown v0.2.5
   Compiling ref-cast-impl v1.0.22
   Compiling float-cmp v0.9.0
   Compiling tracing-core v0.1.32
   Compiling polars-ops v0.38.3
   Compiling num-rational v0.4.1
   Compiling slab v0.4.9
   Compiling paste v1.0.14
   Compiling utf-8 v0.7.6
   Compiling unicode-segmentation v1.11.0
   Compiling xxhash-rust v0.8.10
   Compiling snap v1.1.1
   Compiling precomputed-hash v0.1.1
   Compiling fallible-streaming-iterator v0.1.9
   Compiling string_cache v0.8.7
   Compiling unicode-reverse v1.0.9
   Compiling tendril v0.4.3
   Compiling tracing v0.1.40
   Compiling value-trait v0.8.1
   Compiling rustc_version v0.4.0
   Compiling lexical-core v0.8.5
   Compiling brotli-decompressor v2.5.1
   Compiling http v0.2.12
   Compiling phf v0.10.1
   Compiling safe_arch v0.7.1
   Compiling argminmax v0.6.2
   Compiling futures-task v0.3.30
   Compiling futures-sink v0.3.30
   Compiling rustls v0.21.10
   Compiling strsim v0.10.0
   Compiling ident_case v1.0.1
   Compiling tinyvec_macros v0.1.1
   Compiling hex v0.4.3
   Compiling pin-utils v0.1.0
   Compiling httparse v1.8.0
   Compiling futures-util v0.3.30
   Compiling darling_core v0.20.8
   Compiling tinyvec v1.6.0
   Compiling tokio-util v0.7.10
   Compiling wide v0.7.15
   Compiling brotli v3.5.0
   Compiling simd-json v0.13.9
   Compiling pathfinder_simd v0.5.3
   Compiling streaming-decompression v0.1.2
   Compiling sct v0.7.1
   Compiling rustls-webpki v0.101.7
   Compiling now v0.1.3
   Compiling html5ever v0.26.0
   Compiling approx v0.5.1
   Compiling rustfft v6.2.0
   Compiling bitflags v1.3.2
   Compiling seq-macro v0.3.5
   Compiling try-lock v0.2.5
   Compiling typenum v1.17.0
   Compiling parquet-format-safe v0.2.4
   Compiling want v0.3.1
   Compiling polars-parquet v0.38.3
   Compiling polars-time v0.38.3
   Compiling h2 v0.3.26
   Compiling polars-json v0.38.3
   Compiling darling_macro v0.20.8
   Compiling unicode-normalization v0.1.23
   Compiling http-body v0.4.6
   Compiling form_urlencoded v1.2.1
   Compiling futures-channel v0.3.30
   Compiling fdeflate v0.3.4
   Compiling home v0.5.9
   Compiling winapi-util v0.1.6
   Compiling transpose v0.2.3
   Compiling primal-check v0.3.3
   Compiling polars-plan v0.38.3
   Compiling byteorder v1.5.0
   Compiling color_quant v1.1.0
   Compiling httpdate v1.0.3
   Compiling memmap2 v0.7.1
   Compiling lazy_static v1.4.0
   Compiling tower-service v0.3.2
   Compiling unicode-bidi v0.3.15
   Compiling idna v0.5.0
   Compiling hyper v0.14.28
   Compiling polars-io v0.38.3
   Compiling same-file v1.0.6
   Compiling png v0.17.13
   Compiling darling v0.20.8
   Compiling tokio-rustls v0.24.1
   Compiling xml5ever v0.17.0
   Compiling strum_macros v0.25.3
   Compiling wio v0.2.2
   Compiling polars-lazy v0.38.3
   Compiling num-conv v0.1.0
   Compiling bit-vec v0.6.3
   Compiling powerfmt v0.2.0
   Compiling font-kit v0.11.0
   Compiling time-core v0.1.2
   Compiling plotters-backend v0.3.5
   Compiling jpeg-decoder v0.3.1
   Compiling weezl v0.1.8
   Compiling gif v0.12.0
   Compiling image v0.24.9
   Compiling time-macros v0.2.18
   Compiling deranged v0.3.11
   Compiling bit-set v0.5.3
   Compiling dwrote v0.11.0
   Compiling markup5ever_rcdom v0.2.0
   Compiling hyper-rustls v0.24.2
   Compiling pathfinder_geometry v0.5.1
   Compiling derive_builder_core v0.20.0
   Compiling walkdir v2.5.0
   Compiling url v2.5.0
   Compiling serde_urlencoded v0.7.1
   Compiling simba v0.6.0
   Compiling rustls-pemfile v1.0.4
   Compiling winreg v0.50.0
   Compiling nalgebra-macros v0.1.0
   Compiling async-stream-impl v0.3.5
   Compiling num-iter v0.1.44
   Compiling polars v0.38.3
   Compiling encoding_rs v0.8.34
   Compiling ipnet v2.9.0
   Compiling glob v0.3.1
   Compiling rust_decimal v1.35.0
   Compiling sync_wrapper v0.1.2
   Compiling webpki-roots v0.25.4
   Compiling mime v0.3.17
   Compiling float-ord v0.2.0
   Compiling reqwest v0.11.27
   Compiling num v0.4.2
   Compiling async-stream v0.3.5
   Compiling nalgebra v0.29.0
   Compiling derive_builder_macro v0.20.0
   Compiling select v0.6.0
   Compiling time v0.3.36
   Compiling plotters-bitmap v0.3.3
   Compiling plotters-svg v0.3.5
   Compiling rustdct v0.7.1
   Compiling realfft v3.3.0
   Compiling simba v0.8.1
   Compiling tokio-stream v0.1.15
   Compiling nalgebra-macros v0.2.1
   Compiling arrayvec v0.7.4
   Compiling ttf-parser v0.17.1
   Compiling plotters v0.3.5
   Compiling nalgebra v0.32.5
   Compiling tokio-test v0.4.4
   Compiling ndrustfft v0.4.2
   Compiling yahoo_finance_api v2.1.0
   Compiling derive_builder v0.20.0
   Compiling statrs v0.16.0
   Compiling errorfunctions v0.2.0
   Compiling ndarray-rand v0.14.0
   Compiling RustQuant v0.2.3
   Compiling rest v0.1.0 (G:\work\Program\RustCode\rest)
    Finished dev [unoptimized + debuginfo] target(s) in 8m 43s
     Running `target\debug\rest.exe`
Function = inf
Gradient = [NaN, NaN]
```
4. .\target\.rustc_info.json:
    ```
{"rustc_fingerprint":475279154374054308,"outputs":{"4614504638168534921":{"success":true,"status":"","code":0,"stdout":"rustc 1.77.2 (25ef9e3d8 2024-04-09)\nbinary: rustc\ncommit-hash: 25ef9e3d85d934b27d9dada2f9dd52b1dc63bb04\ncommit-date: 2024-04-09\nhost: x86_64-pc-windows-msvc\nrelease: 1.77.2\nLLVM version: 17.0.6\n","stderr":""},"15729799797837862367":{"success":true,"status":"","code":0,"stdout":"___.exe\nlib___.rlib\n___.dll\n___.dll\n___.lib\n___.dll\nC:\\rust\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\npacked\n___\ndebug_assertions\npanic=\"unwind\"\nproc_macro\ntarget_arch=\"x86_64\"\ntarget_endian=\"little\"\ntarget_env=\"msvc\"\ntarget_family=\"windows\"\ntarget_feature=\"fxsr\"\ntarget_feature=\"sse\"\ntarget_feature=\"sse2\"\ntarget_has_atomic=\"16\"\ntarget_has_atomic=\"32\"\ntarget_has_atomic=\"64\"\ntarget_has_atomic=\"8\"\ntarget_has_atomic=\"ptr\"\ntarget_os=\"windows\"\ntarget_pointer_width=\"64\"\ntarget_vendor=\"pc\"\nwindows\n","stderr":""}},"successes":{}}
```

**Comment by avhz** [comment]
Thanks. And are your toolchains up to date ?

**Comment by harry4939** [comment]
Yes，I updated all toolchains last week

**Comment by avhz** [comment]
Are you able to compile other programs with that tool chain or is it just RustQuant ?

**Comment by harry4939** [comment]
There is no problem compiling other programs with **stable-X86_64－pc-windows-gnu** until RustQuant

**Comment by avhz** [comment]
Hi, is this still an issue ? 
Which toolchain is the default for your machine ?
I unfortunately can't do any testing myself since I don't use Windows.

**Comment by harry4939** [comment]
Yes, the problem are still unsolved
the default toolchain is **stable-x86_64-pc-windows-gnu (default)**
This is not a big issue, I can use the MSVC toolchain, then everything OK. I just want to know why the GNU toolchain is causing problems, I prefer the GNU toolchain 😊
