### ISSUE TITLE
Find workaround for using `#[pyclass]` on a struct with lifetimes. 

### ISSUE THREAD

**Issue by avhz** [avhz/RustQuant#43]
In `autodiff::Variable`, creating Python bindings is currently not possible due to `#[pyclass]` not being compatible on structs that have lifetime annotations, since Rust can no longer keep track of the references. 

What I have:

```rust
/// Struct to contain the initial variables.
#[derive(Clone, Copy, Debug)]
pub struct Variable<'v> {
    /// Pointer to the tape.
    pub tape: &'v Tape,
    /// Index to the node.
    pub index: usize,
    /// Value associated to the node.
    pub value: f64,
}
```

What I wanted:

```rust
use pyo3::prelude::*;

/// Struct to contain the initial variables.
#[derive(Clone, Copy, Debug)]
#[pyclass]                           // <- This
pub struct Variable<'v> {
    /// Pointer to the tape.
    pub tape: &'v Tape,
    /// Index to the node.
    pub index: usize,
    /// Value associated to the node.
    pub value: f64,
}
```

I possibly need to change the `Variable` implementation such that it no longer uses explicit lifetime annotations. Open to suggestions.

**Comment by aatmunbaxi** [comment]
Unfortunately this is not possible with borrowed references. The documentation suggests using a reference-counted pointer object such as `Arc` or `Py`, however. 

More: https://pyo3.rs/v0.18.3/class.html?highlight=lifetime#restrictions
