### ISSUE TITLE
Need suggestions on how to structure the Python bindings. 

### ISSUE THREAD

**Issue by avhz** [avhz/RustQuant#44]
It seems like a tedious task to maintain two separate libraries, one for "base" RustQuant and a separate one for the Python bindings. 

Is there a better way? 
I don't want to litter the base library with things like `#[pyclass]`, `#[new]` and `#[pymethods`, but keeping two separate copies seems unnecessary.

**Comment by SimonG85** [comment]
Hi, I think the best should be to put methods and classes you want to expose in python inside a directory "python" (I saw it inside crate).
Maybe I can help you. Let me know a method you want to expose in python and I can try to make a PR.
A big problem with PyO3 is that is not possible to use generics and lifetime...
