### ISSUE TITLE
`autodiff::graphviz`: make `bgcolor="transparent";` for graphs.

### ISSUE THREAD

**Issue by avhz** [avhz/RustQuant#55]

**Comment by Harshal662** [comment]
I can do that

**Comment by spoloxs** [comment]
`digraph Tape {
        rankdir="LR";
        node [shape=box3d];
        0 [label="Input: x_0, Value: 2.00", color="red"];
        1 [label="Input: x_1, Value: 3.00", color="red"];
        2 [label="Op: #2"];
        3 [label="Op: #3"];
        4 [label="Op: #4"];
        0 -> 2 [label="∂_0: 3.00"];
        1 -> 2 [label="∂_1: 2.00"];
        2 -> 3 [label="∂_0: 403.43"];
        3 -> 4 [label="∂_0: 0.26"];
}
digraph Tape {
        rankdir="LR";
        node [shape=box3d];
        0 [label="Input: x_0, Value: 1.00", color="red"];
        1 [label="Input: x_1, Value: 2.00", color="red"];
        2 [label="Op: #2"];
        3 [label="Op: #3"];
        4 [label="Op: #4"];
        0 -> 2 [label="∂_0: 2.00"];
        1 -> 2 [label="∂_1: 1.00"];
        1 -> 3 [label="∂_0: -0.42"];
        2 -> 4 [label="∂_0: 1.00"];
        3 -> 4 [label="∂_1: 1.00"];
}
digraph Tape {
        rankdir="LR";
        node [shape=box3d];
        0 [label="Input: x_0, Value: 1.00", color="red"];
        1 [label="Input: x_1, Value: 2.00", color="red"];
        2 [label="Input: x_2, Value: 3.00", color="red"];
        3 [label="Input: x_3, Value: 4.00", color="red"];
        4 [label="Op: #4"];
        5 [label="Op: #5"];
        6 [label="Op: #6"];
        7 [label="Op: #7"];
        8 [label="Input: x_8, Value: 5.00", color="red"];
        9 [label="Op: #9"];
        10 [label="Op: #10"];
        11 [label="Op: #11"];
        12 [label="Op: #12"];
        13 [label="Op: #13"];
        14 [label="Op: #14"];
        0 -> 4 [label="∂_0: 2.72"];
        1 -> 5 [label="∂_0: 0.21"];
        4 -> 6 [label="∂_0: 1.00"];
        5 -> 6 [label="∂_1: 1.00"];
        6 -> 7 [label="∂_0: -0.67"];
        2 -> 9 [label="∂_0: 0.29"];
        3 -> 10 [label="∂_0: 8.00"];
        3 -> 10 [label="∂_1: 0.00"];
        9 -> 11 [label="∂_0: 1.00"];
        10 -> 11 [label="∂_1: 1.00"];
        11 -> 12 [label="∂_0: 0.06"];
        8 -> 13 [label="∂_0: 2.88"];
        12 -> 13 [label="∂_1: 5.00"];
        7 -> 14 [label="∂_0: 1.00"];
        13 -> 14 [label="∂_1: 1.00"];
}
Gradient: [-1.8212, -0.1407, 0.0814, 2.2558, 2.8754]`

From this output I can see you are using shape=box3d which is already having transparent bg.. I don't think there is anything need for doing. If I am looking at wrong file please correct me
