### ISSUE TITLE
Migrate another library

### ISSUE THREAD

**Issue by dancixx** [avhz/RustQuant#59]
Hi @avhz 

i have started to develop a stochastic library in rust too. If you approve I can migrate my code and processes into your library, because I dont want to make a totally different like this. It would be great if the community has one strong and featuredull quant and stochastic analysis library in rust. 

https://github.com/dancixx/stochastic-rs

**Comment by dancixx** [comment]
Davies-Harte generator family provides a circulant embedding algorithm to generate fractional stochastic processes. In this algorithm, we can calculate the eigenvalues of the matrix using FFT which can be really fast.
https://arxiv.org/pdf/1308.0399.pdf

**Comment by Autoparallel** [comment]
What's the status of this? @dancixx do you have bridge processes built?

**Comment by dancixx** [comment]
@Autoparallel I'm working on this, but the summer was too busy. My main goal is to add support for the fractional processes in this library and support the fractional models too.

**Comment by Autoparallel** [comment]
Sounds good. Let me know if I can be of help. There's a lot to learn in this repo and from the contributors!

**Comment by dancixx** [comment]
@Autoparallel  The hardest thing is to implement the circulant embedding algorithm using the libs contribution requirements because for efficient data generation, I don't want to use the Euler scheme but rather the FFT.

**Comment by dancixx** [comment]
@Autoparallel first step: https://github.com/avhz/RustQuant/pull/97
