### ISSUE TITLE
`RustQuant::interactive`: Implement User Interface.

### ISSUE THREAD

**Issue by avhz** [avhz/RustQuant#62]
I want to have a TUI or GUI to accompany the library, such that users can have an interactive way to use the library. 

Ideally, all the main modules would have an interface in the UI, but some things like the following would be priorities:

- Instrument pricing.
- Getting data from files or online, and persisting it (Postgres?, JSON?) for later use. 
- Autodiff (enter a function, play with the gradient, plot via Graphviz, etc).
- Create a portfolio, keep track of it, etc.

**Comment by joshleveck** [comment]
Hey! Are you still wanting to do this? If so, do you have examples/inspiration of what kind of features you want to do?

**Comment by joshleveck** [comment]
Tick-rs is really cool. I'm thinking something like tick-rs but you can have overlays of different computations of the data. But I think that's a huge undertaking. Maybe I'll look to something else
