### ISSUE TITLE
`RustQuant::ml`: implement `neural_networks`.

### ISSUE THREAD

**Issue by avhz** [avhz/RustQuant#63]

**Comment by WenqingZong** [comment]
Hi, I'd like to take this issue. :-)

**Comment by WenqingZong** [comment]
Now I understand why you put `difficult` label to this issue. I'm still trying to connect `ndarray` with your auto diff implementation. 

Also, the `activation.rs` needs further modification, currently it's only doing pure math calculation without the support for auto diff.

**Comment by WenqingZong** [comment]
Thanks, BTW, may I ask why you developed your own auto diff module instead of using some existing crate?
